//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CCSDatabaseEntities : DbContext
    {
        public CCSDatabaseEntities()
            : base("name=CCSDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asientos_Contables> Asientos_Contables { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Tipos_Documentos> Tipos_Documentos { get; set; }
        public virtual DbSet<Tipos_Movimientos> Tipos_Movimientos { get; set; }
        public virtual DbSet<Trasnsaccione> Trasnsacciones { get; set; }
    }
}
