//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trasnsaccione
    {
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public int ID_Tipos_Movimientos { get; set; }
        public int ID_Tipos_Documentos { get; set; }
        public int Numero_Documento { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual Tipos_Documentos Tipos_Documentos { get; set; }
        public virtual Tipos_Movimientos Tipos_Movimientos { get; set; }
    }
}
